apiVersion: frp.yejiayu.github.com/v1alpha1
kind: Proxy
metadata:
  labels:
    app.kubernetes.io/name: proxy
    app.kubernetes.io/instance: proxy-sample
    app.kubernetes.io/part-of: frp-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: frp-operator
  name: proxy-sample
spec:
  # TODO(user): Add fields here
